Root:
  Feb[:]:
    RawUdpPrbsTx:
      PacketLength: 0x207 # 8320
      TrigDly: 26041 # 6 kHz
      AxiEn: True
      TxEn: True
      FwCnt: False
    RssiPrbsTx:
      AxiEn: True
      TxEn: False # Disabled TX
      FwCnt: False
