#!/usr/bin/python
##############################################################################
## This file is part of 'LCLS2 AMC Carrier Firmware'.
## It is subject to the license terms in the LICENSE.txt file found in the 
## top-level directory of this distribution and at: 
##    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html. 
## No part of 'LCLS2 AMC Carrier Firmware', including this file, 
## may be copied, modified, propagated, or distributed except according to 
## the terms contained in the LICENSE.txt file.
##############################################################################

import os, sys
from subprocess import check_call

## Define the GIT submodule path and TAG-ing
tagConfig = [ ['/firmware/submodules/amc-carrier-core', '9c45ba3bc760fce22fc225e06b386a684cb771ab'],
              ['/firmware/submodules/lcls-timing-core', 'dd0851d408326aeaca530336e1297432ad4973b5'],
              ['/firmware/submodules/ruckus',           'f06359285a975591d512dae99ccf576077e21775'],
              ['/firmware/submodules/surf',             '0bd4782367a1bca8aafbc4a515463e697cdd7f43'],
              ['/firmware/submodules/sysgen-dsp-lib',   '011ce6d78b031834af713be1796d90d7dbf879b5'] ]

# Check that the submodule paths exists
for i in range(len(tagConfig)):
    path = os.getcwd() + tagConfig[i][0] + '/'
    if (os.path.isdir(path) != True) :
        print "Error: " + path + " does NOT exist"
        sys.exit(-1) 

# Commit the before modifying submodule tags
try:
    check_call('git commit -m "backing up progress via set_submodule_tag script"', shell=True)
except:
    print ""

## Loop through the submodules
for i in range(len(tagConfig)):
    # Generate a list of shell commands
    cmd  = 'cd ' + (os.getcwd() + tagConfig[i][0]) + '/; '
    cmd += 'pwd; '
    cmd += 'git fetch; '
    cmd += 'git checkout ' + tagConfig[i][1] + '; '
    cmd += 'git pull; '
    cmd += 'cd ' + os.getcwd() + '; '
    cmd += 'git add ' + (os.getcwd() + tagConfig[i][0]) + '; '
    # Execut the list of commands
    check_call(cmd, shell=True)
        
# Commit the updated submodule tags
try:
    check_call('git commit -m "Updating submodules tags"', shell=True)
except:
    print ""

##################################################################################################
## Warning: This script does NOT push the commits to github.  You will need to do that manually
##################################################################################################
     
##################################################################################################
## NOTE: You MUST have your SSH keys configured on GITHUB for this script to work
##       https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/
##       https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/
##################################################################################################


