##############################################################################
## This file is part of 'LCLS2 LLRF Development'.
## It is subject to the license terms in the LICENSE.txt file found in the 
## top-level directory of this distribution and at: 
##    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html. 
## No part of 'LCLS2 LLRF Development', including this file, 
## may be copied, modified, propagated, or distributed except according to 
## the terms contained in the LICENSE.txt file.
##############################################################################

# Secondary AMC Auxiliary Power Enable Port
set_property -dict { PACKAGE_PIN H23 IOSTANDARD LVCMOS25 } [get_ports {enAuxPwrL}] 

#######################
## Application Ports ##
#######################

# # RTM's High Speed Ports
set_property PACKAGE_PIN B6 [get_ports {rtmHsTxP}]
set_property PACKAGE_PIN B5 [get_ports {rtmHsTxN}]
set_property PACKAGE_PIN A4 [get_ports {rtmHsRxP}]
set_property PACKAGE_PIN A3 [get_ports {rtmHsRxN}]

# # Spare Clock reference
set_property PACKAGE_PIN P6 [get_ports {genClkP}]
set_property PACKAGE_PIN P5 [get_ports {genClkN}]

# # AMC's JESD Ports
# set_property PACKAGE_PIN AH6 [get_ports {jesdTxP[0][0]}]
# set_property PACKAGE_PIN AH5 [get_ports {jesdTxN[0][0]}]
# set_property PACKAGE_PIN AH2 [get_ports {jesdRxP[0][0]}]
# set_property PACKAGE_PIN AH1 [get_ports {jesdRxN[0][0]}]
# set_property PACKAGE_PIN AG4 [get_ports {jesdTxP[0][1]}]
# set_property PACKAGE_PIN AG3 [get_ports {jesdTxN[0][1]}]
# set_property PACKAGE_PIN AF2 [get_ports {jesdRxP[0][1]}]
# set_property PACKAGE_PIN AF1 [get_ports {jesdRxN[0][1]}]
# set_property PACKAGE_PIN AE4 [get_ports {jesdTxP[0][2]}]
# set_property PACKAGE_PIN AE3 [get_ports {jesdTxN[0][2]}]
# set_property PACKAGE_PIN AD2 [get_ports {jesdRxP[0][2]}]
# set_property PACKAGE_PIN AD1 [get_ports {jesdRxN[0][2]}]
# set_property PACKAGE_PIN AC4 [get_ports {jesdTxP[0][3]}]
# set_property PACKAGE_PIN AC3 [get_ports {jesdTxN[0][3]}]
# set_property PACKAGE_PIN AB2 [get_ports {jesdRxP[0][3]}]
# set_property PACKAGE_PIN AB1 [get_ports {jesdRxN[0][3]}]
# set_property PACKAGE_PIN AN4 [get_ports {jesdTxP[0][4]}]
# set_property PACKAGE_PIN AN3 [get_ports {jesdTxN[0][4]}]
# set_property PACKAGE_PIN AP2 [get_ports {jesdRxP[0][4]}]
# set_property PACKAGE_PIN AP1 [get_ports {jesdRxN[0][4]}]
# set_property PACKAGE_PIN AM6 [get_ports {jesdTxP[0][5]}]
# set_property PACKAGE_PIN AM5 [get_ports {jesdTxN[0][5]}]
# set_property PACKAGE_PIN AM2 [get_ports {jesdRxP[0][5]}]
# set_property PACKAGE_PIN AM1 [get_ports {jesdRxN[0][5]}]
# set_property PACKAGE_PIN AL4 [get_ports {jesdTxP[0][6]}]
# set_property PACKAGE_PIN AL3 [get_ports {jesdTxN[0][6]}]
# set_property PACKAGE_PIN AK2 [get_ports {jesdRxP[0][6]}]
# set_property PACKAGE_PIN AK1 [get_ports {jesdRxN[0][6]}]

set_property PACKAGE_PIN N4 [get_ports {jesdTxP[1][0]}]
set_property PACKAGE_PIN N3 [get_ports {jesdTxN[1][0]}]
set_property PACKAGE_PIN M2 [get_ports {jesdRxP[1][0]}]
set_property PACKAGE_PIN M1 [get_ports {jesdRxN[1][0]}]
set_property PACKAGE_PIN L4 [get_ports {jesdTxP[1][1]}]
set_property PACKAGE_PIN L3 [get_ports {jesdTxN[1][1]}]
set_property PACKAGE_PIN K2 [get_ports {jesdRxP[1][1]}]
set_property PACKAGE_PIN K1 [get_ports {jesdRxN[1][1]}]
set_property PACKAGE_PIN J4 [get_ports {jesdTxP[1][2]}]
set_property PACKAGE_PIN J3 [get_ports {jesdTxN[1][2]}]
set_property PACKAGE_PIN H2 [get_ports {jesdRxP[1][2]}]
set_property PACKAGE_PIN H1 [get_ports {jesdRxN[1][2]}]
set_property PACKAGE_PIN G4 [get_ports {jesdTxP[1][3]}]
set_property PACKAGE_PIN G3 [get_ports {jesdTxN[1][3]}]
set_property PACKAGE_PIN F2 [get_ports {jesdRxP[1][3]}]
set_property PACKAGE_PIN F1 [get_ports {jesdRxN[1][3]}]
set_property PACKAGE_PIN F6 [get_ports {jesdTxP[1][4]}]
set_property PACKAGE_PIN F5 [get_ports {jesdTxN[1][4]}]
set_property PACKAGE_PIN E4 [get_ports {jesdRxP[1][4]}]
set_property PACKAGE_PIN E3 [get_ports {jesdRxN[1][4]}]
set_property PACKAGE_PIN D6 [get_ports {jesdTxP[1][5]}]
set_property PACKAGE_PIN D5 [get_ports {jesdTxN[1][5]}]
set_property PACKAGE_PIN D2 [get_ports {jesdRxP[1][5]}]
set_property PACKAGE_PIN D1 [get_ports {jesdRxN[1][5]}]
# set_property PACKAGE_PIN C4 [get_ports {jesdTxP[1][6]}]
# set_property PACKAGE_PIN C3 [get_ports {jesdTxN[1][6]}]
# set_property PACKAGE_PIN B2 [get_ports {jesdRxP[1][6]}]
# set_property PACKAGE_PIN B1 [get_ports {jesdRxN[1][6]}]

# set_property PACKAGE_PIN AB6 [get_ports {jesdClkP[0][0]}]
# set_property PACKAGE_PIN AB5 [get_ports {jesdClkN[0][0]}]
# set_property PACKAGE_PIN AF6 [get_ports {jesdClkP[0][1]}]
# set_property PACKAGE_PIN AF5 [get_ports {jesdClkN[0][1]}]
# set_property PACKAGE_PIN AD6 [get_ports {jesdClkP[0][2]}]
# set_property PACKAGE_PIN AD5 [get_ports {jesdClkN[0][2]}]
set_property PACKAGE_PIN M6  [get_ports {jesdClkP[1][0]}]
set_property PACKAGE_PIN M5  [get_ports {jesdClkN[1][0]}]
# set_property PACKAGE_PIN K6  [get_ports {jesdClkP[1][1]}]
# set_property PACKAGE_PIN K5  [get_ports {jesdClkN[1][1]}]
# set_property PACKAGE_PIN H6  [get_ports {jesdClkP[1][2]}]
# set_property PACKAGE_PIN H5  [get_ports {jesdClkN[1][2]}]

# # AMC's JTAG Ports jtagPri[1][0-4] remapped for SPI 
set_property -dict { PACKAGE_PIN AP9  IOSTANDARD LVCMOS25 PULLUP true} [get_ports {spiSdio_io}] 
set_property -dict { PACKAGE_PIN AL10 IOSTANDARD LVCMOS25 PULLUP true} [get_ports {spiSclk_o}] 
set_property -dict { PACKAGE_PIN AM10 IOSTANDARD LVCMOS25 PULLUP true} [get_ports {spiSdi_o}] 
set_property -dict { PACKAGE_PIN AH9  IOSTANDARD LVCMOS25 PULLUP true} [get_ports {spiSdo_i}] 
set_property -dict { PACKAGE_PIN AH8  IOSTANDARD LVCMOS25 PULLUP true} [get_ports {spiCsL_o[0]}]

 # AMC's Spare Ports remapped for SPI
 set_property -dict { PACKAGE_PIN Y23  IOSTANDARD LVCMOS18 PULLUP true} [get_ports {spiCsL_o[1]}] 
 set_property -dict { PACKAGE_PIN AA23 IOSTANDARD LVCMOS18 PULLUP true} [get_ports {spiCsL_o[2]}] 
 set_property -dict { PACKAGE_PIN AA24 IOSTANDARD LVCMOS18 PULLUP true} [get_ports {spiCsL_o[3]}]
 set_property -dict { PACKAGE_PIN W25  IOSTANDARD LVCMOS18 PULLUP true} [get_ports {spiSclkDac_o}] 
 set_property -dict { PACKAGE_PIN Y25  IOSTANDARD LVCMOS18 PULLUP true} [get_ports {spiCsLDac_o}]
 set_property -dict { PACKAGE_PIN W23  IOSTANDARD LVCMOS18 PULLUP true} [get_ports {spiSdioDac_io}] 

 set_property -dict { PACKAGE_PIN W24  IOSTANDARD LVCMOS18 } [get_ports {trigHW}] 

# # AMC's System Reference Ports
# set_property -dict { PACKAGE_PIN AE32 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {sysRefP[0][0]}] 
# set_property -dict { PACKAGE_PIN AF32 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {sysRefN[0][0]}] 
# set_property -dict { PACKAGE_PIN AF33 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {sysRefP[0][1]}] 
# set_property -dict { PACKAGE_PIN AG34 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {sysRefN[0][1]}] 
# set_property -dict { PACKAGE_PIN AA34 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {sysRefP[0][2]}] 
# set_property -dict { PACKAGE_PIN AB34 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {sysRefN[0][2]}] 
# set_property -dict { PACKAGE_PIN AA29 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {sysRefP[0][3]}] 
# set_property -dict { PACKAGE_PIN AB29 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {sysRefN[0][3]}] 

# set_property -dict { PACKAGE_PIN AG31 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {sysRefP[1][0]}] 
# set_property -dict { PACKAGE_PIN AG32 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {sysRefN[1][0]}] 
# set_property -dict { PACKAGE_PIN AF30 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {sysRefP[1][1]}] 
# set_property -dict { PACKAGE_PIN AG30 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {sysRefN[1][1]}] 
 set_property -dict { PACKAGE_PIN AC34 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {sysRefP[1][0]}] 
 set_property -dict { PACKAGE_PIN AD34 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {sysRefN[1][0]}] 
# set_property -dict { PACKAGE_PIN AE33 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {sysRefP[1][3]}] 
# set_property -dict { PACKAGE_PIN AF34 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {sysRefN[1][3]}] 

# AMC's Sync Ports remapped for LLRF
 set_property -dict { PACKAGE_PIN AM22 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {syncInP[1][0]}] 
 set_property -dict { PACKAGE_PIN AN22 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {syncInN[1][0]}] 


 set_property -dict { PACKAGE_PIN Y31  IOSTANDARD LVDS  } [get_ports {syncOutP[1][0]}] 
 set_property -dict { PACKAGE_PIN Y32  IOSTANDARD LVDS  } [get_ports {syncOutN[1][0]}]  
 set_property -dict { PACKAGE_PIN AF20 IOSTANDARD LVDS  } [get_ports {syncOutP[1][1]}] 
 set_property -dict { PACKAGE_PIN AG20 IOSTANDARD LVDS  } [get_ports {syncOutN[1][1]}]  
 set_property -dict { PACKAGE_PIN AM21 IOSTANDARD LVDS  } [get_ports {syncOutP[1][2]}] 
 set_property -dict { PACKAGE_PIN AN21 IOSTANDARD LVDS  } [get_ports {syncOutN[1][2]}]

# # RTM's Low Speed Ports
# set_property -dict { PACKAGE_PIN AK31 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[0]}] 
# set_property -dict { PACKAGE_PIN AK32 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[0]}] 
# set_property -dict { PACKAGE_PIN AJ29 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[1]}] 
# set_property -dict { PACKAGE_PIN AK30 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[1]}] 
# set_property -dict { PACKAGE_PIN AL30 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[2]}] 
# set_property -dict { PACKAGE_PIN AM30 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[2]}] 
# set_property -dict { PACKAGE_PIN AL29 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[3]}] 
# set_property -dict { PACKAGE_PIN AM29 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[3]}] 
# set_property -dict { PACKAGE_PIN AL34 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[4]}] 
# set_property -dict { PACKAGE_PIN AM34 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[4]}] 
# set_property -dict { PACKAGE_PIN AM32 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[5]}] 
# set_property -dict { PACKAGE_PIN AN32 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[5]}] 
# set_property -dict { PACKAGE_PIN AN34 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[6]}] 
# set_property -dict { PACKAGE_PIN AP34 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[6]}] 
# set_property -dict { PACKAGE_PIN AN31 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[7]}] 
# set_property -dict { PACKAGE_PIN AP31 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[7]}] 
# set_property -dict { PACKAGE_PIN AN33 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[8]}] 
# set_property -dict { PACKAGE_PIN AP33 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[8]}] 
# set_property -dict { PACKAGE_PIN AL32 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[9]}] 
# set_property -dict { PACKAGE_PIN AL33 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[9]}] 
# set_property -dict { PACKAGE_PIN AH34 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[10]}] 
# set_property -dict { PACKAGE_PIN AJ34 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[10]}] 
# set_property -dict { PACKAGE_PIN AH31 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[11]}] 
# set_property -dict { PACKAGE_PIN AH32 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[11]}] 
# set_property -dict { PACKAGE_PIN AH33 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[12]}] 
# set_property -dict { PACKAGE_PIN AJ33 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[12]}] 
# set_property -dict { PACKAGE_PIN AJ30 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[13]}] 
# set_property -dict { PACKAGE_PIN AJ31 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[13]}] 
# set_property -dict { PACKAGE_PIN AN29 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[14]}] 
# set_property -dict { PACKAGE_PIN AP30 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[14]}] 
# set_property -dict { PACKAGE_PIN AN27 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[15]}] 
# set_property -dict { PACKAGE_PIN AN28 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[15]}] 
# set_property -dict { PACKAGE_PIN AP28 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[16]}] 
# set_property -dict { PACKAGE_PIN AP29 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[16]}] 
# set_property -dict { PACKAGE_PIN AN26 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[17]}] 
# set_property -dict { PACKAGE_PIN AP26 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[17]}] 
# set_property -dict { PACKAGE_PIN AJ28 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[18]}] 
# set_property -dict { PACKAGE_PIN AK28 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[18]}] 
# set_property -dict { PACKAGE_PIN AH27 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[19]}] 
# set_property -dict { PACKAGE_PIN AH28 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[19]}] 
# set_property -dict { PACKAGE_PIN AL27 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[20]}] 
# set_property -dict { PACKAGE_PIN AL28 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[20]}] 
# set_property -dict { PACKAGE_PIN AK26 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[21]}] 
# set_property -dict { PACKAGE_PIN AK27 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[21]}] 
# set_property -dict { PACKAGE_PIN AM26 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[22]}] 
# set_property -dict { PACKAGE_PIN AM27 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[22]}] 
# set_property -dict { PACKAGE_PIN AH26 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsP[23]}] 
# set_property -dict { PACKAGE_PIN AJ26 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {rtmLsN[23]}] 
set_property -dict { PACKAGE_PIN AE27 IOSTANDARD LVDS } [get_ports {rtmLsP[24]}] 
set_property -dict { PACKAGE_PIN AF27 IOSTANDARD LVDS } [get_ports {rtmLsN[24]}] 
set_property -dict { PACKAGE_PIN AM12 IOSTANDARD LVDS_25 } [get_ports {rtmLsP[25]}] 
set_property -dict { PACKAGE_PIN AN12 IOSTANDARD LVDS_25 } [get_ports {rtmLsN[25]}] 
set_property -dict { PACKAGE_PIN AM11 IOSTANDARD LVDS_25 } [get_ports {rtmLsP[26]}] 
set_property -dict { PACKAGE_PIN AN11 IOSTANDARD LVDS_25 } [get_ports {rtmLsN[26]}] 
set_property -dict { PACKAGE_PIN AN13 IOSTANDARD LVDS_25 } [get_ports {rtmLsP[27]}] 
set_property -dict { PACKAGE_PIN AP13 IOSTANDARD LVDS_25 } [get_ports {rtmLsN[27]}] 
set_property -dict { PACKAGE_PIN K20  IOSTANDARD LVDS_25 } [get_ports {rtmLsP[28]}] 
set_property -dict { PACKAGE_PIN K21  IOSTANDARD LVDS_25 } [get_ports {rtmLsN[28]}] 
set_property -dict { PACKAGE_PIN N21  IOSTANDARD LVDS_25 } [get_ports {rtmLsP[29]}] 
set_property -dict { PACKAGE_PIN M21  IOSTANDARD LVDS_25 } [get_ports {rtmLsN[29]}] 
set_property -dict { PACKAGE_PIN M20  IOSTANDARD LVDS_25 } [get_ports {rtmLsP[30]}] 
set_property -dict { PACKAGE_PIN L20  IOSTANDARD LVDS_25 } [get_ports {rtmLsN[30]}] 
set_property -dict { PACKAGE_PIN R21  IOSTANDARD LVDS_25 } [get_ports {rtmLsP[31]}] 
set_property -dict { PACKAGE_PIN R22  IOSTANDARD LVDS_25 } [get_ports {rtmLsN[31]}] 
# set_property -dict { PACKAGE_PIN P20  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsP[32]}] 
# set_property -dict { PACKAGE_PIN P21  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsN[32]}] 
# set_property -dict { PACKAGE_PIN N22  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsP[33]}] 
# set_property -dict { PACKAGE_PIN M22  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsN[33]}] 
# set_property -dict { PACKAGE_PIN R23  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsP[34]}] 
# set_property -dict { PACKAGE_PIN P23  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsN[34]}] 
# set_property -dict { PACKAGE_PIN R25  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsP[35]}] 
# set_property -dict { PACKAGE_PIN R26  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsN[35]}] 
# set_property -dict { PACKAGE_PIN T24  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsP[36]}] 
# set_property -dict { PACKAGE_PIN T25  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsN[36]}] 
# set_property -dict { PACKAGE_PIN T27  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsP[37]}] 
# set_property -dict { PACKAGE_PIN R27  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsN[37]}] 
# set_property -dict { PACKAGE_PIN P24  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsP[38]}] 
# set_property -dict { PACKAGE_PIN P25  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsN[38]}] 
# set_property -dict { PACKAGE_PIN P26  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsP[39]}] 
# set_property -dict { PACKAGE_PIN N26  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsN[39]}] 
# set_property -dict { PACKAGE_PIN N24  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsP[40]}] 
# set_property -dict { PACKAGE_PIN M24  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsN[40]}] 
# set_property -dict { PACKAGE_PIN M25  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsP[41]}] 
# set_property -dict { PACKAGE_PIN M26  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsN[41]}] 
# set_property -dict { PACKAGE_PIN L22  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsP[42]}] 
# set_property -dict { PACKAGE_PIN K23  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsN[42]}] 
# set_property -dict { PACKAGE_PIN L25  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsP[43]}] 
# set_property -dict { PACKAGE_PIN K25  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsN[43]}] 
# set_property -dict { PACKAGE_PIN L23  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsP[44]}] 
# set_property -dict { PACKAGE_PIN L24  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsN[44]}] 
# set_property -dict { PACKAGE_PIN M27  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsP[45]}] 
# set_property -dict { PACKAGE_PIN L27  IOSTANDARD LVDS_25 DIFF_TERM TRUE } [get_ports {rtmLsN[45]}]

# # Backplane Ports
# set_property -dict { PACKAGE_PIN AD19 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxP[1]}] 
# set_property -dict { PACKAGE_PIN AD18 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxN[1]}] 
# set_property -dict { PACKAGE_PIN AG15 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxP[2]}] 
# set_property -dict { PACKAGE_PIN AG14 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxN[2]}] 
# set_property -dict { PACKAGE_PIN AG19 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxP[3]}] 
# set_property -dict { PACKAGE_PIN AH19 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxN[3]}] 
# set_property -dict { PACKAGE_PIN AJ15 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxP[4]}] 
# set_property -dict { PACKAGE_PIN AJ14 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxN[4]}] 
# set_property -dict { PACKAGE_PIN AG17 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxP[5]}] 
# set_property -dict { PACKAGE_PIN AG16 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxN[5]}] 
# set_property -dict { PACKAGE_PIN AL18 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxP[6]}] 
# set_property -dict { PACKAGE_PIN AL17 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxN[6]}] 
# set_property -dict { PACKAGE_PIN AK15 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxP[7]}] 
# set_property -dict { PACKAGE_PIN AL15 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxN[7]}] 
# set_property -dict { PACKAGE_PIN AL19 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxP[8]}] 
# set_property -dict { PACKAGE_PIN AM19 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxN[8]}] 
# set_property -dict { PACKAGE_PIN AL14 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxP[9]}] 
# set_property -dict { PACKAGE_PIN AM14 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxN[9]}] 
# set_property -dict { PACKAGE_PIN AP16 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxP[10]}] 
# set_property -dict { PACKAGE_PIN AP15 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxN[10]}] 
# set_property -dict { PACKAGE_PIN AM16 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxP[11]}] 
# set_property -dict { PACKAGE_PIN AM15 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxN[11]}] 
# set_property -dict { PACKAGE_PIN AN18 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxP[12]}] 
# set_property -dict { PACKAGE_PIN AN17 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxN[12]}] 
# set_property -dict { PACKAGE_PIN AM17 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxP[13]}] 
# set_property -dict { PACKAGE_PIN AN16 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxN[13]}] 
# set_property -dict { PACKAGE_PIN AN19 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxP[14]}] 
# set_property -dict { PACKAGE_PIN AP18 IOSTANDARD LVDS DIFF_TERM TRUE } [get_ports {bpFabRxN[14]}] 

# set_property -dict { PACKAGE_PIN AP11 IOSTANDARD LVDS_25 } [get_ports {bpTxP}] 
# set_property -dict { PACKAGE_PIN AP10 IOSTANDARD LVDS_25 } [get_ports {bpTxN}] 

# set_property -dict { PACKAGE_PIN AF9  IOSTANDARD LVCMOS25 } [get_ports {bpClkIn[0]}] 
# set_property -dict { PACKAGE_PIN AF10 IOSTANDARD LVCMOS25 } [get_ports {bpClkIn[1]}] 
# set_property -dict { PACKAGE_PIN AG11 IOSTANDARD LVCMOS25 } [get_ports {bpClkIn[2]}] 
# set_property -dict { PACKAGE_PIN AG12 IOSTANDARD LVCMOS25 } [get_ports {bpClkIn[3]}] 
# set_property -dict { PACKAGE_PIN AF8  IOSTANDARD LVCMOS25 } [get_ports {bpClkIn[4]}] 
# set_property -dict { PACKAGE_PIN AJ11 IOSTANDARD LVCMOS25 } [get_ports {bpClkIn[5]}] 

# set_property -dict { PACKAGE_PIN AG9  IOSTANDARD LVCMOS25 } [get_ports {bpClkOut[0]}] 
# set_property -dict { PACKAGE_PIN AG10 IOSTANDARD LVCMOS25 } [get_ports {bpClkOut[1]}] 
# set_property -dict { PACKAGE_PIN AH11 IOSTANDARD LVCMOS25 } [get_ports {bpClkOut[2]}] 
# set_property -dict { PACKAGE_PIN AH12 IOSTANDARD LVCMOS25 } [get_ports {bpClkOut[3]}] 
# set_property -dict { PACKAGE_PIN AJ10 IOSTANDARD LVCMOS25 } [get_ports {bpClkOut[4]}] 
# set_property -dict { PACKAGE_PIN AE13 IOSTANDARD LVCMOS25 } [get_ports {bpClkOut[5]}] 

# DDR3L SO-DIMM Ports
set_property PACKAGE_PIN      G17         [get_ports {ddrClkP}] 
set_property PACKAGE_PIN      G16         [get_ports {ddrClkN}] 
set_property IOSTANDARD       DIFF_HSTL_I [get_ports {ddrClkP ddrClkN}]
set_property IBUF_LOW_PWR     FALSE       [get_ports {ddrClkP ddrClkN}]
set_property PULLTYPE         KEEPER      [get_ports {ddrClkP ddrClkN}]

set_property PACKAGE_PIN B10 [get_ports {ddrDqsP[0]}] 
set_property PACKAGE_PIN A10 [get_ports {ddrDqsN[0]}] 
set_property PACKAGE_PIN K10 [get_ports {ddrDqsP[1]}] 
set_property PACKAGE_PIN J10 [get_ports {ddrDqsN[1]}] 
set_property PACKAGE_PIN L13 [get_ports {ddrDqsP[2]}] 
set_property PACKAGE_PIN K13 [get_ports {ddrDqsN[2]}] 
set_property PACKAGE_PIN F13 [get_ports {ddrDqsP[3]}] 
set_property PACKAGE_PIN E13 [get_ports {ddrDqsN[3]}] 
set_property PACKAGE_PIN B29 [get_ports {ddrDqsP[4]}] 
set_property PACKAGE_PIN A29 [get_ports {ddrDqsN[4]}] 
set_property PACKAGE_PIN B24 [get_ports {ddrDqsP[5]}] 
set_property PACKAGE_PIN A24 [get_ports {ddrDqsN[5]}] 
set_property PACKAGE_PIN C21 [get_ports {ddrDqsP[6]}] 
set_property PACKAGE_PIN C22 [get_ports {ddrDqsN[6]}] 
set_property PACKAGE_PIN G20 [get_ports {ddrDqsP[7]}] 
set_property PACKAGE_PIN F20 [get_ports {ddrDqsN[7]}] 
set_property IOSTANDARD DIFF_SSTL15_DCI   [get_ports {ddrDqsP[*] ddrDqsN[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ddrDqsP[*] ddrDqsN[*]}]
set_property SLEW          FAST           [get_ports {ddrDqsP[*] ddrDqsN[*]}]
set_property IBUF_LOW_PWR  FALSE          [get_ports {ddrDqsP[*] ddrDqsN[*]}]
set_property ODT           RTT_40         [get_ports {ddrDqsP[*] ddrDqsN[*]}]

set_property PACKAGE_PIN F8  [get_ports {ddrDm[0]}] 
set_property PACKAGE_PIN L8  [get_ports {ddrDm[1]}] 
set_property PACKAGE_PIN H11 [get_ports {ddrDm[2]}] 
set_property PACKAGE_PIN E11 [get_ports {ddrDm[3]}] 
set_property PACKAGE_PIN F27 [get_ports {ddrDm[4]}] 
set_property PACKAGE_PIN E26 [get_ports {ddrDm[5]}] 
set_property PACKAGE_PIN D23 [get_ports {ddrDm[6]}] 
set_property PACKAGE_PIN G24 [get_ports {ddrDm[7]}] 
set_property IOSTANDARD SSTL15_DCI        [get_ports {ddrDm[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ddrDm[*]}]
set_property SLEW FAST                    [get_ports {ddrDm[*]}]

set_property PACKAGE_PIN B9  [get_ports {ddrDq[0]}] 
set_property PACKAGE_PIN A9  [get_ports {ddrDq[1]}] 
set_property PACKAGE_PIN D8  [get_ports {ddrDq[2]}] 
set_property PACKAGE_PIN C8  [get_ports {ddrDq[3]}] 
set_property PACKAGE_PIN D9  [get_ports {ddrDq[4]}] 
set_property PACKAGE_PIN C9  [get_ports {ddrDq[5]}] 
set_property PACKAGE_PIN E10 [get_ports {ddrDq[6]}] 
set_property PACKAGE_PIN D10 [get_ports {ddrDq[7]}] 
set_property PACKAGE_PIN J9  [get_ports {ddrDq[8]}] 
set_property PACKAGE_PIN H9  [get_ports {ddrDq[9]}] 
set_property PACKAGE_PIN J8  [get_ports {ddrDq[10]}] 
set_property PACKAGE_PIN H8  [get_ports {ddrDq[11]}] 
set_property PACKAGE_PIN G9  [get_ports {ddrDq[12]}] 
set_property PACKAGE_PIN F9  [get_ports {ddrDq[13]}] 
set_property PACKAGE_PIN G10 [get_ports {ddrDq[14]}] 
set_property PACKAGE_PIN F10 [get_ports {ddrDq[15]}] 
set_property PACKAGE_PIN H12 [get_ports {ddrDq[16]}] 
set_property PACKAGE_PIN G12 [get_ports {ddrDq[17]}] 
set_property PACKAGE_PIN K11 [get_ports {ddrDq[18]}] 
set_property PACKAGE_PIN J11 [get_ports {ddrDq[19]}] 
set_property PACKAGE_PIN L12 [get_ports {ddrDq[20]}] 
set_property PACKAGE_PIN K12 [get_ports {ddrDq[21]}] 
set_property PACKAGE_PIN J13 [get_ports {ddrDq[22]}] 
set_property PACKAGE_PIN H13 [get_ports {ddrDq[23]}] 
set_property PACKAGE_PIN C12 [get_ports {ddrDq[24]}] 
set_property PACKAGE_PIN B12 [get_ports {ddrDq[25]}] 
set_property PACKAGE_PIN C11 [get_ports {ddrDq[26]}] 
set_property PACKAGE_PIN B11 [get_ports {ddrDq[27]}] 
set_property PACKAGE_PIN A13 [get_ports {ddrDq[28]}] 
set_property PACKAGE_PIN A12 [get_ports {ddrDq[29]}] 
set_property PACKAGE_PIN D13 [get_ports {ddrDq[30]}] 
set_property PACKAGE_PIN C13 [get_ports {ddrDq[31]}] 
set_property PACKAGE_PIN C27 [get_ports {ddrDq[32]}] 
set_property PACKAGE_PIN B27 [get_ports {ddrDq[33]}] 
set_property PACKAGE_PIN E28 [get_ports {ddrDq[34]}] 
set_property PACKAGE_PIN D29 [get_ports {ddrDq[35]}] 
set_property PACKAGE_PIN D28 [get_ports {ddrDq[36]}] 
set_property PACKAGE_PIN C28 [get_ports {ddrDq[37]}] 
set_property PACKAGE_PIN A27 [get_ports {ddrDq[38]}] 
set_property PACKAGE_PIN A28 [get_ports {ddrDq[39]}] 
set_property PACKAGE_PIN B25 [get_ports {ddrDq[40]}] 
set_property PACKAGE_PIN A25 [get_ports {ddrDq[41]}] 
set_property PACKAGE_PIN C26 [get_ports {ddrDq[42]}] 
set_property PACKAGE_PIN B26 [get_ports {ddrDq[43]}] 
set_property PACKAGE_PIN E25 [get_ports {ddrDq[44]}] 
set_property PACKAGE_PIN D25 [get_ports {ddrDq[45]}] 
set_property PACKAGE_PIN D24 [get_ports {ddrDq[46]}] 
set_property PACKAGE_PIN C24 [get_ports {ddrDq[47]}] 
set_property PACKAGE_PIN E22 [get_ports {ddrDq[48]}] 
set_property PACKAGE_PIN E23 [get_ports {ddrDq[49]}] 
set_property PACKAGE_PIN B21 [get_ports {ddrDq[50]}] 
set_property PACKAGE_PIN B22 [get_ports {ddrDq[51]}] 
set_property PACKAGE_PIN B20 [get_ports {ddrDq[52]}] 
set_property PACKAGE_PIN A20 [get_ports {ddrDq[53]}] 
set_property PACKAGE_PIN D20 [get_ports {ddrDq[54]}] 
set_property PACKAGE_PIN D21 [get_ports {ddrDq[55]}] 
set_property PACKAGE_PIN E20 [get_ports {ddrDq[56]}] 
set_property PACKAGE_PIN E21 [get_ports {ddrDq[57]}] 
set_property PACKAGE_PIN F23 [get_ports {ddrDq[58]}] 
set_property PACKAGE_PIN F24 [get_ports {ddrDq[59]}] 
set_property PACKAGE_PIN G22 [get_ports {ddrDq[60]}] 
set_property PACKAGE_PIN F22 [get_ports {ddrDq[61]}] 
set_property PACKAGE_PIN H21 [get_ports {ddrDq[62]}] 
set_property PACKAGE_PIN G21 [get_ports {ddrDq[63]}] 
set_property IOSTANDARD SSTL15_DCI        [get_ports {ddrDq[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ddrDq[*]}]
set_property SLEW          FAST           [get_ports {ddrDq[*]}]
set_property IBUF_LOW_PWR  FALSE          [get_ports {ddrDq[*]}]
set_property ODT           RTT_40         [get_ports {ddrDq[*]}]

set_property PACKAGE_PIN B14 [get_ports {ddrA[0]}] 
set_property PACKAGE_PIN A14 [get_ports {ddrA[1]}] 
set_property PACKAGE_PIN A19 [get_ports {ddrA[2]}] 
set_property PACKAGE_PIN A18 [get_ports {ddrA[3]}] 
set_property PACKAGE_PIN B15 [get_ports {ddrA[4]}] 
set_property PACKAGE_PIN A15 [get_ports {ddrA[5]}] 
set_property PACKAGE_PIN B17 [get_ports {ddrA[6]}] 
set_property PACKAGE_PIN B16 [get_ports {ddrA[7]}] 
set_property PACKAGE_PIN C18 [get_ports {ddrA[8]}] 
set_property PACKAGE_PIN C17 [get_ports {ddrA[9]}] 
set_property PACKAGE_PIN D14 [get_ports {ddrA[10]}] 
set_property PACKAGE_PIN C14 [get_ports {ddrA[11]}] 
set_property PACKAGE_PIN E15 [get_ports {ddrA[12]}] 
set_property PACKAGE_PIN D15 [get_ports {ddrA[13]}] 
set_property PACKAGE_PIN F15 [get_ports {ddrA[14]}] 
set_property PACKAGE_PIN F14 [get_ports {ddrA[15]}]
set_property IOSTANDARD SSTL15_DCI        [get_ports {ddrA[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ddrA[*]}]
set_property SLEW FAST                    [get_ports {ddrA[*]}]

set_property PACKAGE_PIN D19 [get_ports {ddrBa[0]}] 
set_property PACKAGE_PIN D18 [get_ports {ddrBa[1]}] 
set_property PACKAGE_PIN E16 [get_ports {ddrBa[2]}] 
set_property IOSTANDARD SSTL15_DCI        [get_ports {ddrBa[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ddrBa[*]}]
set_property SLEW FAST                    [get_ports {ddrBa[*]}]

set_property PACKAGE_PIN D16 [get_ports {ddrCsL[0]}] 
set_property PACKAGE_PIN L15 [get_ports {ddrCsL[1]}] 
set_property IOSTANDARD SSTL15_DCI        [get_ports {ddrCsL[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ddrCsL[*]}]
set_property SLEW FAST                    [get_ports {ddrCsL[*]}]

set_property PACKAGE_PIN E17 [get_ports {ddrOdt[0]}] 
set_property PACKAGE_PIN K15 [get_ports {ddrOdt[1]}] 
set_property IOSTANDARD SSTL15_DCI        [get_ports {ddrOdt[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ddrOdt[*]}]
set_property SLEW FAST                    [get_ports {ddrOdt[*]}]

set_property PACKAGE_PIN E18 [get_ports {ddrCke[0]}] 
set_property PACKAGE_PIN H18 [get_ports {ddrCke[1]}] 
set_property IOSTANDARD SSTL15_DCI        [get_ports {ddrCke[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ddrCke[*]}]
set_property SLEW FAST                    [get_ports {ddrCke[*]}]

set_property PACKAGE_PIN C19 [get_ports {ddrCkP[0]}] 
set_property PACKAGE_PIN B19 [get_ports {ddrCkN[0]}] 
set_property PACKAGE_PIN H17 [get_ports {ddrCkP[1]}] 
set_property PACKAGE_PIN H16 [get_ports {ddrCkN[1]}] 
set_property IOSTANDARD DIFF_SSTL15_DCI   [get_ports {ddrCkP[*] ddrCkN[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ddrCkP[*] ddrCkN[*]}]
set_property SLEW FAST                    [get_ports {ddrCkP[*] ddrCkN[*]}]

set_property -dict { PACKAGE_PIN G15 IOSTANDARD SSTL15_DCI OUTPUT_IMPEDANCE RDRV_40_40 SLEW FAST } [get_ports {ddrWeL}] 
set_property -dict { PACKAGE_PIN F18 IOSTANDARD SSTL15_DCI OUTPUT_IMPEDANCE RDRV_40_40 SLEW FAST } [get_ports {ddrRasL}] 
set_property -dict { PACKAGE_PIN F17 IOSTANDARD SSTL15_DCI OUTPUT_IMPEDANCE RDRV_40_40 SLEW FAST } [get_ports {ddrCasL}] 
set_property -dict { PACKAGE_PIN C16 IOSTANDARD SSTL15     OUTPUT_IMPEDANCE RDRV_48_48 SLEW SLOW } [get_ports {ddrRstL}] 
set_property -dict { PACKAGE_PIN L19 IOSTANDARD LVCMOS15 } [get_ports {ddrScl}] 
set_property -dict { PACKAGE_PIN L18 IOSTANDARD LVCMOS15 } [get_ports {ddrSda}] 
set_property -dict { PACKAGE_PIN K17 IOSTANDARD LVCMOS15 } [get_ports {ddrPwrEnL}] 

set_property CLOCK_DEDICATED_ROUTE FALSE    [get_nets {U_DdrMem/refClock}]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets {U_DdrMem/refClkBufg}]

create_clock -name ddrClkIn   -period  5.000  [get_pins {U_DdrMem/BUFG_Inst/O}]
#create_generated_clock -name ddrIntClk0   [get_pins {U_DdrMem/MigCore_Inst/inst/u_ddr3_mem_intfc/u_mig_ddr3_phy/inst/u_ddr3_infrastructure/mmcme3_adv_inst/CLKOUT0}]
#create_generated_clock -name ddrIntClk1   [get_pins {U_DdrMem/MigCore_Inst/inst/u_ddr3_mem_intfc/u_mig_ddr3_phy/inst/u_ddr3_infrastructure/u_bufg_riuClk/O}]

set_multicycle_path -setup 8 -from [get_pins -hier -filter {NAME =~ */u_ddr_mc_cal/u_ddr_cal/calDone*/C}]
set_multicycle_path -end -hold 7 -from [get_pins -hier -filter {NAME =~ */u_ddr_mc_cal/u_ddr_cal/calDone*/C}]
set_false_path -hold -to [get_pins -hier -filter {NAME =~ *.u_xiphy_control/xiphy_control/RIU_ADDR*}]
set_false_path -hold -to [get_pins -hier -filter {NAME =~ *.u_xiphy_control/xiphy_control/RIU_WR_DATA*}]



####################################
## Application Timing Constraints ##
####################################
create_clock -period 6.400 -name pgpRefClk [get_ports genClkP]

create_generated_clock -name pgpClk -source [get_ports genClkP] -multiply_by 1 \
    [get_pins ClockManager7_PGP/MmcmGen.U_Mmcm/CLKOUT0]

create_clock -period 5.405 -name jesdRefClk [get_ports {jesdClkP[1][0]}]

create_generated_clock -name jesdClk -divide_by 1 -source [get_ports {jesdClkP[1][0]}] \
    [get_pins {U_App/ClockManager_JESD/MmcmGen.U_Mmcm/CLKOUT0}]
    
create_generated_clock -name jesdClk370  -multiply_by 2 -source [get_ports {jesdClkP[1][0]}] \
    [get_pins {U_App/ClockManager_JESD/MmcmGen.U_Mmcm/CLKOUT1}]


set_clock_groups -asynchronous\
 -group [get_clocks -include_generated_clocks pgpRefClk]\
 -group [get_clocks -include_generated_clocks pgpClk]\ 
 -group [get_clocks -include_generated_clocks jesdRefClk]\
 -group [get_clocks -include_generated_clocks jesdClk]\
 -group [get_clocks -include_generated_clocks ddrClkIn]


# set_clock_groups -asynchronous -group [get_clocks {fabClk}] -group [get_clocks {jesdRefClk}]
# set_clock_groups -asynchronous -group [get_clocks {fabClk}] -group [get_clocks {jesdClk}]
# set_clock_groups -asynchronous -group [get_clocks {fabClk}] -group [get_clocks {jesdClk370}]

#set_clock_groups -asynchronous -group [get_clocks {jesdClk}] -group [get_clocks {jesdClk370}]
#set_clock_groups -asynchronous\
# -group [get_clocks -include_generated_clocks pgpRefClk]\
# -group [get_clocks -include_generated_clocks jesdRefClk]

#set_clock_groups -asynchronous \
#    -group [get_clocks -include_generated_clocks {pgpRefClk}] \
#    -group [get_clocks -include_generated_clocks {ddrClkIn}] 

# set_clock_groups -asynchronous -group [get_clocks {pgpRefClk}] -group [get_clocks {ddrIntClk0}] 
# set_clock_groups -asynchronous -group [get_clocks {pgpRefClk}] -group [get_clocks {ddrIntClk1}] 


set_property ASYNC_REG true [get_cells -hierarchical *crossDomainSyncReg_reg*]

##########################
## Misc. Configurations ##
##########################

# Bitstream generation options
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property CFGBVS GND [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 1 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]
