          LmkReg_0x0100: 0x08
          LmkReg_0x0101: 0x55
          LmkReg_0x0103: 0x00
          LmkReg_0x0104: 0x22
          LmkReg_0x0105: 0x00
          LmkReg_0x0106: 0x70
          LmkReg_0x0107: 0x06
          LmkReg_0x0108: 0x61
          LmkReg_0x0109: 0x55
          LmkReg_0x010B: 0x01
          LmkReg_0x010C: 0x22
          LmkReg_0x010D: 0x00
          LmkReg_0x010E: 0x70
          LmkReg_0x010F: 0x9E
          LmkReg_0x0110: 0x61
          LmkReg_0x0111: 0x55
          LmkReg_0x0113: 0x01
          LmkReg_0x0114: 0x22
          LmkReg_0x0115: 0x00
          LmkReg_0x0116: 0x70
          LmkReg_0x0117: 0x9E
          LmkReg_0x0118: 0x61
          LmkReg_0x0119: 0x55
          LmkReg_0x011B: 0x02
          LmkReg_0x011C: 0x22
          LmkReg_0x011D: 0x00
          LmkReg_0x011E: 0x70
          LmkReg_0x011F: 0x00
          LmkReg_0x0120: 0x61
          LmkReg_0x0121: 0x55
          LmkReg_0x0123: 0x01
          LmkReg_0x0124: 0x22
          LmkReg_0x0125: 0x00
          LmkReg_0x0126: 0x70
          LmkReg_0x0127: 0x9E
          LmkReg_0x0128: 0x61
          LmkReg_0x0129: 0x55
          LmkReg_0x012B: 0x01
          LmkReg_0x012C: 0x22
          LmkReg_0x012D: 0x00
          LmkReg_0x012E: 0x70
          LmkReg_0x012F: 0x9E
          LmkReg_0x0130: 0x08
          LmkReg_0x0131: 0x55
          LmkReg_0x0133: 0x00
          LmkReg_0x0134: 0x22
          LmkReg_0x0135: 0x00
          LmkReg_0x0136: 0x70
          LmkReg_0x0137: 0x16
          LmkReg_0x0138: 0x00
          LmkReg_0x0139: 0x03
          LmkReg_0x013A: 0x04
          LmkReg_0x013B: 0x00
          LmkReg_0x013C: 0x00
          LmkReg_0x013D: 0x08
          LmkReg_0x013E: 0x03
          LmkReg_0x013F: 0x00
          LmkReg_0x0140: 0x00
          LmkReg_0x0141: 0x00
          LmkReg_0x0142: 0x00
          LmkReg_0x0143: 0x11
          LmkReg_0x0144: 0xFF
          LmkReg_0x0145: 0x7F
          LmkReg_0x0146: 0x10
          LmkReg_0x0147: 0x1A
          LmkReg_0x0148: 0x02
          LmkReg_0x0149: 0x42
          LmkReg_0x014A: 0x33
          LmkReg_0x014B: 0x16
          LmkReg_0x014C: 0x00
          LmkReg_0x014D: 0x00
          LmkReg_0x014E: 0x00
          LmkReg_0x014F: 0x7F
          LmkReg_0x0150: 0x01
          LmkReg_0x0151: 0x02
          LmkReg_0x0152: 0x00
          LmkReg_0x0153: 0x00
          LmkReg_0x0154: 0x78
          LmkReg_0x0155: 0x00
          LmkReg_0x0156: 0x7D
          LmkReg_0x0157: 0x00
          LmkReg_0x0158: 0x96
          LmkReg_0x0159: 0x06
          LmkReg_0x015A: 0x00
          LmkReg_0x015B: 0xD4
          LmkReg_0x015C: 0x20
          LmkReg_0x015D: 0x00
          LmkReg_0x015E: 0x00
          LmkReg_0x015F: 0x0B
          LmkReg_0x0160: 0x00
          LmkReg_0x0161: 0x01
          LmkReg_0x0162: 0x84
          LmkReg_0x0163: 0x00
          LmkReg_0x0164: 0x00
          LmkReg_0x0165: 0x05
          LmkReg_0x0171: 0xAA
          LmkReg_0x0172: 0x02
          LmkReg_0x0173: 0x0 
          LmkReg_0x0174: 0x0 
          LmkReg_0x017C: 0x15
          LmkReg_0x017D: 0x33
          LmkReg_0x0166: 0x00
          LmkReg_0x0167: 0x00
          LmkReg_0x0168: 0x05
          LmkReg_0x0169: 0x59
          LmkReg_0x016A: 0x20
          LmkReg_0x016B: 0x00
          LmkReg_0x016C: 0x00
          LmkReg_0x016D: 0x00
          LmkReg_0x016E: 0x13
