# Define target part
export PRJ_PART = XCU55N-FSVH2892-2L-E

# Define target output
target: prom

# Define TOP_DIR path
export TOP_DIR = $(abspath $(PWD)/../..)

# Use top level makefile
include $(TOP_DIR)/targets/shared_config.mk
include $(TOP_DIR)/submodules/ruckus/system_vivado.mk
