          DacReg[0]: 0x0218   # Sets board to 4X interpolation
          DacReg[1]: 0x0003   
          DacReg[2]: 0x2050   # 16 bits, mixer on, NCO on, not two's compliment data
          DacReg[3]: 0xA300   # May need to set to 0xA301, then A300
          DacReg[4]: 0xF0F0   # This masks lanes 7,6,5,4 fifo and lane errors.  Uros had it masking lanes 7,6,5,4,3,2 because this was for the demo board that only had two lanes I think.
          DacReg[5]: 0xFF07   # Not sure here.  This is masking some sysref errors, Uros had it only masking serdes block 0 and 1 PLL locks and the DAC PLL lock alarm
          DacReg[6]: 0xFFFF   # Set as eval board, is making a bunch of alarms 
          DacReg[7]: 0x3800
          DacReg[8]: 0x0000
          DacReg[9]: 0x0000
          DacReg[10]: 0x0000
          DacReg[11]: 0x0000
          DacReg[12]: 0x0400
          DacReg[13]: 0x0400
          DacReg[14]: 0x0400
          DacReg[15]: 0x0400
          DacReg[16]: 0x0000
          DacReg[17]: 0x0000
          DacReg[18]: 0x0000
          DacReg[19]: 0x0000
          DacReg[20]: 0x0000
          DacReg[21]: 0x0000
          DacReg[22]: 0x4E20  # This is the upper 16 bits of the NCO frequency for the DACAB path
          DacReg[23]: 0x0000
          DacReg[24]: 0x0000
          DacReg[25]: 0x4E20  # This is the upper 16 bits of the NCO frequency for the DACCD path
          DacReg[26]: 0x0020
          DacReg[27]: 0x0000
          DacReg[28]: 0x0000
          DacReg[29]: 0x0000
          DacReg[30]: 0x9999
          DacReg[31]: 0x9980
          DacReg[32]: 0x8008
          DacReg[33]: 0x0000
          DacReg[34]: 0x1B1B  # Sets where samples go from JESD.  Datapath D goes to DACD, Datapath C goes to DACC, DatapathB goes to DACB and DatapathA goes to DACA
          DacReg[35]: 0x01FF  # This routes the "sleep terminal signal"  we don't use this so, it doesn't matter.
          DacReg[36]: 0x0020  # Use only the next sysref pulse.  Uros had it set to NOT use the sysref pulse
          DacReg[37]: 0x4000  # DACCLK div 4 to get JESD clock Uros had DACCLK=JESDCLK
          DacReg[38]: 0x0000
          DacReg[39]: 0x0000
          DacReg[40]: 0x0013
          DacReg[41]: 0xffff
          DacReg[42]: 0x0000
          DacReg[43]: 0x0000
          DacReg[44]: 0x0000
          DacReg[45]: 0x0000
          DacReg[46]: 0xffff
          DacReg[47]: 0x0004
          DacReg[48]: 0x0000
          DacReg[49]: 0x1000
          DacReg[50]: 0x0000
          DacReg[51]: 0x0000
          DacReg[52]: 0x0000
          DacReg[53]: 0x0000
          DacReg[54]: 0x0000
          DacReg[55]: 0x0000
          DacReg[56]: 0x0000
          DacReg[57]: 0x0000
          DacReg[58]: 0x0000
          DacReg[59]: 0x1800  # Set's divide amount for SERDES PLL ref clock divider (looks like it's set to 3?)
          DacReg[60]: 0x0028  # Set's PLL multiply factor - eval set to: 14
          DacReg[61]: 0x0088  # Set's EQ and offset correction on, not sure how to configure this
          DacReg[62]: 0x0108  # JESD termination setting and rate.  Only difference is Uros had LOS enabled.
          DacReg[63]: 0x0000  # Swaping on JESD polarity.  I don't think we have and DAC JESD lanes swapped.
          DacReg[64]: 0x0000
          DacReg[65]: 0x0000
          DacReg[66]: 0x0000
          DacReg[67]: 0x0000
          DacReg[68]: 0x0000
          DacReg[69]: 0x0000
          DacReg[70]: 0x0044
          DacReg[71]: 0x190a
          DacReg[72]: 0x31c3
          DacReg[73]: 0x0000  # JESD Link selection.  Seems it should be set like the eval board.
          DacReg[74]: 0x0f01  # Turns on serdes 0-3 and does NOT reset JESD reset.
          DacReg[75]: 0x0801  # Number of octates per fram (1) and elastic buffers as set on eval board
          DacReg[76]: 0x0903  # Number of JESD lanes being use (3 - means 4) and 9 frames per multifame.  
          DacReg[77]: 0x0300  # Number of converters per link - 4
          DacReg[78]: 0x0f0f
          DacReg[79]: 0x1c61
          DacReg[80]: 0x0000
          DacReg[81]: 0x00DC  # Set's which errors cause a sync request (lane 0).  Use eval board settings
          DacReg[82]: 0x00ff
          DacReg[83]: 0x0000
          DacReg[84]: 0x00FC  # Set's which errors cause a sync request (lane 1).  Use eval board settings
          DacReg[85]: 0x00ff
          DacReg[86]: 0x0000
          DacReg[87]: 0x00ff
          DacReg[88]: 0x00ff
          DacReg[89]: 0x0000
          DacReg[90]: 0x00ff
          DacReg[91]: 0x00ff
          DacReg[92]: 0x1133  # Set up sysref mode for links - use eval board settings
          DacReg[93]: 0x0000
          DacReg[94]: 0x0000
          DacReg[95]: 0x3210  # cross switch for JESDlanes, not sure we want this as it may depend on their board - this set up is serds0 to jesdlane4, serdes1 to jesdlane2, serdes2 to jesdlane1, serdes3 to jesdlane0
          DacReg[96]: 0x5764  # More cross switching SD4 to JD7, SD6 to JD6, SD7 to JD5, SD5 to JD4
          DacReg[97]: 0x0211
          DacReg[98]: 0x0000
          DacReg[99]: 0x0000
          DacReg[100]: 0x1003
          DacReg[101]: 0x1003
          DacReg[102]: 0x3701
          DacReg[103]: 0xf30e
          DacReg[104]: 0xf90b
          DacReg[105]: 0x4a0b
          DacReg[106]: 0x170f
          DacReg[107]: 0xee0c
          DacReg[108]: 0x0007
          DacReg[109]: 0x00ff
          DacReg[110]: 0x0000
          DacReg[111]: 0x0000
          DacReg[112]: 0x0000
          DacReg[113]: 0x0000
          DacReg[114]: 0x0000
          DacReg[115]: 0x0000
          DacReg[116]: 0x0000
          DacReg[117]: 0x0000
          DacReg[118]: 0x0000
          DacReg[119]: 0x0000
          DacReg[120]: 0x0000
          DacReg[121]: 0x0000
          DacReg[122]: 0x0000
          DacReg[123]: 0x0000
          DacReg[124]: 0x0000
          DacReg[125]: 0x0000