pcie:
  Core:
    #####################################
    # Configure Link[0] (QSFP[0].lane[0])
    #####################################
    EthLane[0]:
      EthConfig:
        # Set the local MAC address
        LocalMac: 08:00:56:00:45:50 
        # Set the local IP address
        LocalIp: 192.168.2.1  
        # Don't bypass any RSSI modules (only for FSBL)
        BypRssi: 0x0                
      ############################
      UdpClient[0]:
        ClientRemotePort: 8192
        ClientRemoteIp: 192.168.2.10    
      ############################
      UdpClient[1]: # Slot#3 Link
        ClientRemotePort: 8192
        ClientRemoteIp: 192.168.2.11
      ############################
      UdpClient[2]: # Slot#4 Link
        ClientRemotePort: 8192
        ClientRemoteIp: 192.168.2.12 
      ############################
      UdpClient[3]: # Slot#5 Link
        ClientRemotePort: 8192
        ClientRemoteIp: 192.168.2.13 
      ############################
      UdpClient[4]: # Slot#6 Link
        ClientRemotePort: 8192
        ClientRemoteIp: 192.168.2.14 
      ############################
      UdpClient[5]: # Slot#7 Link
        ClientRemotePort: 8192
        ClientRemoteIp: 192.168.2.15 
      #####################################
      # Open the RSSI connections for links
      #####################################
      RssiClient[:]:
        OpenConn: 0x1
        CloseConn: 0x0       
        HeaderChksumEn: 0x1
        