pcie:
  Core:  
########################################################    
    # UdpBufferGrp:           
      # UdpDebug:
        # MuxSel: PrimaryDMA   
########################################################   
    EthPhyGrp:
      ############################   
      # EthConfig[:]:      
        # TxPreCursor: 0x7
        # TxPostCursor: 0x7
        # TxDiffCtrl: 0xF
      ############################   
      EthConfig[0]:
        # Set the local MAC address
        LocalMac: 00:44:56:FF:00:50
        # Set the local IP address
        LocalIp: 192.168.2.50  
      ############################   
      EthConfig[1]:
        # Set the local MAC address
        LocalMac: 00:44:56:FF:00:51
        # Set the local IP address
        LocalIp: 192.168.2.51
      ############################   
      EthConfig[2]:
        # Set the local MAC address
        LocalMac: 00:44:56:FF:00:52
        # Set the local IP address
        LocalIp: 192.168.2.52
      ############################   
      EthConfig[3]:
        # Set the local MAC address
        LocalMac: 00:44:56:FF:00:53
        # Set the local IP address
        LocalIp: 192.168.2.53  
      ############################   
      EthConfig[4]:
        # Set the local MAC address
        LocalMac: 00:44:56:FF:00:54
        # Set the local IP address
        LocalIp: 192.168.2.54
      ############################   
      EthConfig[5]:
        # Set the local MAC address
        LocalMac: 00:44:56:FF:00:55
        # Set the local IP address
        LocalIp: 192.168.2.55
      ############################   
########################################################    
    UdpGrp:
      ############################    
      UdpConfig[:]:
        EnKeepAlive: 0x1
        KeepAliveConfig: 0x2E90EDD0 # 5 seconds    
      ############################    
      UdpEngine[:]:
        ClientRemotePort[0]: 8198 # UDP_SRV_RSSI_ILEAVE_IDX_C = Interleaved RSSI UDP server on AMC carrier
        ClientRemotePort[1]: 8195 # UDP_SRV_BP_MGS_IDX_C = UDP server for Backplane Messaging on AMC carrier  
      ############################    
      RssiClient[:]:   
        OpenConn: 0x1
        CloseConn: 0x0          
      ############################     
      UdpEngine[0]:  
        ClientRemoteIp[:]: 192.168.2.10 # Slot#2 Link 
      ############################   
      UdpEngine[1]:  
        ClientRemoteIp[:]: 192.168.2.11 # Slot#3 Link 
      ############################     
      UdpEngine[2]:  
        ClientRemoteIp[:]: 192.168.2.12 # Slot#4 Link 
      ############################     
      UdpEngine[3]:  
        ClientRemoteIp[:]: 192.168.2.13 # Slot#5 Link 
      ############################     
      UdpEngine[4]:  
        ClientRemoteIp[:]: 192.168.2.14 # Slot#6 Link 
      ############################     
      UdpEngine[5]:  
        ClientRemoteIp[:]: 192.168.2.15 # Slot#7 Link 
      ############################       
########################################################    
