pcie:
  Core:
    #####################################
    # Configure Link[0] (QSFP[0].lane[0])
    #####################################
    EthLane[0]:
      EthConfig:
        # Set the local MAC address
        LocalMac: 00:44:56:01:02:03
        # Set the local IP address
        LocalIp: 192.168.2.69
        # Don't bypass any RSSI modules (only for FSBL)
        BypRssi: 0x0                
      ############################
      UdpEngine:
        ClientRemotePort[:]: 8192
        # # ClientRemotePort[:]: 0
        # ClientRemotePort[0]: 8192
        # ClientRemotePort[1]: 8192
        ClientRemoteIp[0]: 192.168.2.10 # Slot#2 Link    
        ClientRemoteIp[1]: 192.168.2.11 # Slot#3 Link
        ClientRemoteIp[2]: 192.168.2.12 # Slot#4 Link
        ClientRemoteIp[3]: 192.168.2.13 # Slot#5 Link
        ClientRemoteIp[4]: 192.168.2.14 # Slot#6 Link        
        ClientRemoteIp[5]: 192.168.2.15 # Slot#7 Link
      #####################################
      # Open the RSSI connections for links
      #####################################
      RssiClient[:]:   
        OpenConn: 0x1
        CloseConn: 0x0       
        # Mode: 0x1
        # HeaderChksumEn: 0x1
        # CumAckTimeout: 1 # ms
        # RetransTimeout: 250 # ms
        # NullSegTimeout: 1000 # ms
        # MaxCumAck: 4
        
        