pcie:
  Core:
    #####################################
    # Configure Link[0] (QSFP[0].lane[0])
    #####################################
    EthLane[0]:
      EthConfig:
        # Set the local MAC address
        LocalMac: 08:00:56:00:45:50 
        # Set the local IP address
        LocalIp: 10.0.3.99          
        # Don't bypass any RSSI modules (only for FSBL)
        BypRssi: 0x0                
      ############################
      UdpEngine:
        ClientRemotePort[:]: 8198
        ClientRemoteIp[0]: 10.0.3.102 # Slot#2 Link    
        ClientRemoteIp[1]: 10.0.3.103 # Slot#3 Link
        ClientRemoteIp[2]: 10.0.3.104 # Slot#4 Link
        ClientRemoteIp[3]: 10.0.3.105 # Slot#5 Link
        ClientRemoteIp[4]: 10.0.3.106 # Slot#6 Link        
        ClientRemoteIp[5]: 10.0.3.107 # Slot#7 Link   
      #####################################
      # Open the RSSI connections for links
      #####################################
      RssiClient[:]:
        OpenConn: 0x1
        CloseConn: 0x0       
        HeaderChksumEn: 0x1
        