pcie:
  Core:
    EthLane[:]:
      ############################    
      EthConfig:
        EnKeepAlive: 0x1
        KeepAliveConfig: 0x2E90EDD0 # 5 seconds
      ############################    
      RssiClient:   
        OpenConn: 0x1
        CloseConn: 0x0      
      ############################    
      UdpEngine:
        ClientRemotePort[0]: 8198 # UDP_SRV_RSSI_ILEAVE_IDX_C = Interleaved RSSI UDP server on AMC carrier
        ClientRemotePort[1]: 8195 # UDP_SRV_BP_MGS_IDX_C = UDP server for Backplane Messaging on AMC carrier
########################################################    
    EthLane[0]:
########################################################     
      EthConfig:
        # Set the local MAC address
        LocalMac: 00:44:56:FF:00:50
        # Set the local IP address
        LocalIp: 10.0.3.202  
      ############################    
      UdpEngine:
         ClientRemoteIp[:]: 10.0.3.102 # Slot#2 Link 
########################################################    
    EthLane[1]:
######################################################## 
      EthConfig:
        # Set the local MAC address
        LocalMac: 00:44:56:FF:00:51
        # Set the local IP address
        LocalIp: 10.0.3.203
      ############################    
      UdpEngine:
         ClientRemoteIp[:]: 10.0.3.103 # Slot#3 Link 
########################################################    
    EthLane[2]:
######################################################## 
      EthConfig:
        # Set the local MAC address
        LocalMac: 00:44:56:FF:00:52
        # Set the local IP address
        LocalIp: 10.0.3.204
      ############################    
      UdpEngine:
         ClientRemoteIp[:]: 10.0.3.104 # Slot#4 Link    
########################################################    
    EthLane[3]:
######################################################## 
      EthConfig:
        # Set the local MAC address
        LocalMac: 00:44:56:FF:00:53
        # Set the local IP address
        LocalIp: 10.0.3.205
      ############################    
      UdpEngine:
         ClientRemoteIp[:]: 10.0.3.105 # Slot#5 Link  
########################################################    
    EthLane[4]:
######################################################## 
      EthConfig:
        # Set the local MAC address
        LocalMac: 00:44:56:FF:00:54
        # Set the local IP address
        LocalIp: 10.0.3.206
      ############################    
      UdpEngine:
         ClientRemoteIp[:]: 10.0.3.106 # Slot#6 Link   
########################################################    
    EthLane[5]:
######################################################## 
      EthConfig:
        # Set the local MAC address
        LocalMac: 00:44:56:FF:00:55
        # Set the local IP address
        LocalIp: 10.0.3.207
      ############################    
      UdpEngine:
         ClientRemoteIp[:]: 10.0.3.107 # Slot#7 Link            
######################################################## 
